### ISSUE TITLE
Black and white pdf export for schematics

### ISSUE THREAD

**Issue by MTRNord** [actions-for-kicad/generate-kicad-files#7]
Hi,

Thanks for making this action. Makes this export quick and simple.

Would it be possible to add an option to support black and white only export? Reasoning being that probably the majority of people don't want to print the slightly yellow background which kicad by default exports for schematics :) So for easy printing a b+w option would be nice to have.

**Comment by Nick-v-L** [comment]
Hi,

Thank you for creating the issue. Sorry for the late reply. Started working on this feature in #8.

**Comment by Nick-v-L** [comment]
@MTRNord, thanks again for the feedback. Added in v1.1
